COUNTRIES = [
    {"code": "US", "name": "United States"},
    {"code": "CA", "name": "Canada"},
    {"code": "GB", "name": "United Kingdom"},
    {"code": "AU", "name": "Australia"},
    {"code": "IN", "name": "India"},
    {"code": "SG", "name": "Singapore"},
    {"code": "DE", "name": "Germany"},
    {"code": "FR", "name": "France"},
    {"code": "BR", "name": "Brazil"},
    {"code": "MX", "name": "Mexico"},
]


SUBDIVISIONS = {
    "US": [
        {"code": "AL", "name": "Alabama"},
        {"code": "AK", "name": "Alaska"},
        {"code": "AZ", "name": "Arizona"},
        {"code": "CA", "name": "California"},
        {"code": "CO", "name": "Colorado"},
        {"code": "FL", "name": "Florida"},
        {"code": "GA", "name": "Georgia"},
        {"code": "IL", "name": "Illinois"},
        {"code": "MA", "name": "Massachusetts"},
        {"code": "MD", "name": "Maryland"},
        {"code": "MI", "name": "Michigan"},
        {"code": "NC", "name": "North Carolina"},
        {"code": "NJ", "name": "New Jersey"},
        {"code": "NY", "name": "New York"},
        {"code": "OH", "name": "Ohio"},
        {"code": "PA", "name": "Pennsylvania"},
        {"code": "TN", "name": "Tennessee"},
        {"code": "TX", "name": "Texas"},
        {"code": "UT", "name": "Utah"},
        {"code": "VA", "name": "Virginia"},
        {"code": "WA", "name": "Washington"},
    ],
    "CA": [
        {"code": "AB", "name": "Alberta"},
        {"code": "BC", "name": "British Columbia"},
        {"code": "MB", "name": "Manitoba"},
        {"code": "NB", "name": "New Brunswick"},
        {"code": "NL", "name": "Newfoundland and Labrador"},
        {"code": "NS", "name": "Nova Scotia"},
        {"code": "ON", "name": "Ontario"},
        {"code": "PE", "name": "Prince Edward Island"},
        {"code": "QC", "name": "Quebec"},
        {"code": "SK", "name": "Saskatchewan"},
    ],
    "GB": [
        {"code": "ENG", "name": "England"},
        {"code": "SCT", "name": "Scotland"},
        {"code": "WLS", "name": "Wales"},
        {"code": "NIR", "name": "Northern Ireland"},
    ],
    "AU": [
        {"code": "NSW", "name": "New South Wales"},
        {"code": "VIC", "name": "Victoria"},
        {"code": "QLD", "name": "Queensland"},
        {"code": "WA", "name": "Western Australia"},
        {"code": "SA", "name": "South Australia"},
        {"code": "TAS", "name": "Tasmania"},
        {"code": "ACT", "name": "Australian Capital Territory"},
        {"code": "NT", "name": "Northern Territory"},
    ],
    "IN": [
        {"code": "DL", "name": "Delhi"},
        {"code": "MH", "name": "Maharashtra"},
        {"code": "KA", "name": "Karnataka"},
        {"code": "TN", "name": "Tamil Nadu"},
        {"code": "UP", "name": "Uttar Pradesh"},
        {"code": "GJ", "name": "Gujarat"},
        {"code": "RJ", "name": "Rajasthan"},
        {"code": "WB", "name": "West Bengal"},
    ],
    "SG": [
        {"code": "SG", "name": "Singapore"},
    ],
}
