"""add user onboarding fields

Revision ID: 42865afd04bc
Revises: 0003_user_token_version
Create Date: 2025-12-10 16:40:19.105807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '42865afd04bc'
down_revision: Union[str, None] = '0003_user_token_version'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('preferred_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('mfa_method', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_method')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'preferred_name')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
